name: Build Sussurros

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java 25
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '25'

      - name: Build
        run: ./gradlew build
